[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
# Let the Dockerfile CMD handle startup
# startCommand = "/app/scripts/start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/health"
healthcheckTimeout = 300